### ISSUE TITLE
Shield Block Reduction

### ISSUE THREAD

**Issue by Mythacri** [krbz999/artichron#102]
All shields are currenlty able to block too much damage and are heavily overtuned.

Shield blocking should be reduced as the following:

Buckler: 4d6 -> 2d4
Heater: 4d8 -> 2d6
Kite: 4d10 -> 2d8
Tower: 4d12 -> 2d10

**Comment by krbz999** [comment]
Currently the action of blocking is in the "Defend" activity, which is also used for parrying, so that would need to be taken into account as well.

Like with damage rolls, I will propose we only store the die size. Then *blocking* rolls 2 dice, and parrying rolls 1 die.
