### ISSUE TITLE
Weapon and Armor Triangle

### ISSUE THREAD

**Issue by Mythacri** [krbz999/artichron#107]
Weapons and armor follow a different triangle of strengths and weaknesses than shields. Of the three main types of armors: robes (light), leathers (medium), and plates (heavy); each one has a particular category of weapon that is most effective against it.

While these categories of weapons are yet to be fully settled on, basic logic can help abstract some of these. Weapons that, I other systems, would traditionally slash  such as axes and swords would prices less effective against heavier plate armors. In contrast a weapon that focuses all damage on a single point would be better against these heavier armors. In reverse to this a weapon like a spear that works on heavy armor, would be less effective against someone in robes due to the increased mobility that would generally offer the person wearing them.

**Comment by krbz999** [comment]
Piercing weapons: No benefit, but also no worse damage against any type of armor.
Slashing weapons: Good against those without armor (and worse against armor).
Bludgeoning weapons: ?

Crap where have I seen these before.

**Comment by Mythacri** [comment]
> Piercing weapons: No benefit, but also no worse damage against any type of armor.
> 
> Slashing weapons: Good against those without armor (and worse against armor).
> 
> Bludgeoning weapons: ?
> 
> 
> 
> Crap where have I seen these before.

Well no, piercing weapons would be in fact more effective against heavier armor by bypassing it and aiming for spaces between the plates. Or if you'd rather we could go the for the more brutal route the argument would be that bludgeoning is good against heavy armor, piercing is good against leathers, and slashing is good against light robes. I'm not sure what you're referencing here but we could differentiate things in other ways of course. Two-handed vs one-handed, ranged vs melee, polearms be pommels. Etc.

**Comment by NMyers17** [comment]
Bludgeoning weapons are actually really effective against those in heavier armour. So id say:

- Bludgeoning Weapons: Bonus against heavier armours, and unarmoured but weak against medium armour?

**Comment by krbz999** [comment]
After some discussion, we decided to stick with leaving it for #48 - there won't be a triangle, but specific damage types are reduced by armor (for physical damage) or a specific resistance type.
