### ISSUE TITLE
Build Magic System

### ISSUE THREAD

**Issue by Mythacri** [krbz999/artichron#2]
A simple magic system requires three things:
- Resource Usage
- Spell Purpose
- Spell Shape

If each of these are made to be easy to understand and use then it is possible to combine them in a modular fashion and allow a magic user to create their own spell on the fly. Or it is at least possible to create a great many spells at once.

_BELOW IS A PRELIMINARY SYSTEM SUGGESTION_

**Resource Usage**
For something like this I believe Artichron already has it with its health, stamina, and mana trio of attributes. Mana can easily be spent to add energy to a spell. I would suggest at a base that a spell requires 0 mana and that adding power to it then costs 1 mana scaling upwards.

**Spell Purpose**
Every spell needs a purpose or a type. To make this simple and modular I would recommend assigning something like a die size to each type. The most commonly resisted type of damage or the least impactful of buffs having the largest die. 

By assigning dice like this you can use the standard set of rpg dice and then if need be add individual sizes in between them for online play. 

Mana could then be spent to add additional dice to the pool of damage or ajurative/buffing effect.

**Spell Shape**
Spell shape determines the position, range, and area of a spell. This can also be assigned a die to make it simple and modular; effectively having a player roll 1 to 2 dice at a base for each spell. This shape die would be added to the damage in this case as to my knowledge Artichron has no saving throws or armor class, just damage reduction (which is pretty sweet).

My immediate suggestion here is that the larger the effective area of the spell, the smaller the die that gets added. A blast of fire that targets a small cone of enemies could use a d12 because it is concentrated magic. A large ball or square of magic cast at a long range could use a d6 or even a d4 as it will affect multiple targets.

Mana spent for spell shaping should increase the effective area or number of targets of the spell. A circular spell that begins with a radius of 1 space could have mana added to it to increase its radius. A single target spell could use mana to add an additional target.

**Crafting a Spell**
A spell using this suggested modular system can be crafted with the following.

1. Select a Spell Purpose (die size) 
2. Optional: Select a Spell Shape (die size) 
3. Add additional purpose/damage dice to the pool by expending mana. 
4. Optional: Add additional shape dice, if used, to increase the range/size of the spell by expending mana.
5. Roll all accumulated dice and determine the overall damage/buff of the spell being cast.

**Comment by krbz999** [comment]
It isn't clear to me how "assigning" a die determines a spell's initial range, type (damage type?), and area

**Comment by krbz999** [comment]
It's also not clear to me whether a spell is pre-defined or if it's purpose, range, shape, and damage (and damage type) are decided on when casting.

**Comment by Mythacri** [comment]
> It isn't clear to me how "assigning" a die determines a spell's initial range, type (damage type?), and area

Here's a quick example, finer details added later if you decide this is a concept you like:

Purpose Die:
D8 = Fire Damage
D6 = Lightning Damage
D4 = Arcane Damage

Shape Die:
D12 = Single Target Blast
D6 = A circular area
D8 = A line originating from caster

Example Spell:
Johnny wants to cast a ball of lightning magic at an area of enemies.  Johnny picks up his d6 for lightning damage and then picks up another d6 for the circular area of the spell. The spell will now do 2d6 lightning damage to all enemies in its area. 

Johnny thinks that the enemies he's planning on hitting are a bit tougher than these 2d6 can handle so he is going to spend 1 mana to add an additional die of lightning damage, bringing the spell up a total of 3d6 lightning damage dealt to all enemies in that area.

**Comment by Mythacri** [comment]
> It's also not clear to me whether a spell is pre-defined or if it's purpose, range, shape, and damage (and damage type) are decided on when casting.

I mentioned this at the end of the first paragraph that this concept could be used to either allow magic users to make spells on the fly OR to allow us to make a predetermined, hopefully balanced, list of spells.

**Comment by krbz999** [comment]
OK, I like it. However, there is also the concept of *range* to consider for circular area magic, and the concept of *width* for lines originating from the caster.

**Comment by Mythacri** [comment]
> OK, I like it. However, there is also the concept of *range* to consider for circular area magic, and the concept of *width* for lines originating from the caster.

Yes of course, this would be something I'd work to clean up and explain if the modular magic dice system here was something you found appealing. If it is, I can begin working on expanding it. The only thing I would possibly need would be a list of magical effects you want to include. I.E. fire magic, lightning magic, etc. The buffs we can hold off on until more of the system is in place to determine where they would be effective.

**Comment by krbz999** [comment]
Some preliminary damage types that were discussed are enumerated here: https://github.com/krbz999/artichron/blob/main/module/helpers/config.mjs#L18
