### ISSUE TITLE
Scoping: Ammunition

### ISSUE THREAD

**Issue by InnilToo** [krbz999/artichron#20]
Artichron needs an ammunition system to handle the use of various ammunition types.

### Use Case
A player needs to use different types of ammunition (arrows, bolts, bullets, bombs, etc.) for their ranged weapons, which can affect the weapon's range, template, and damage. Currently, there is no streamlined system to handle the specific attributes and effects of ammunition within the game.

#### MVP
Fields: Ammunition Type, Range, Price, Weight, Quantity, Template, Conditions, Damage.
- **Ammunition Type:** Categories like arrows, bolts, bullets, bombs, etc. (Weapons could define which type can be used on them.)
- **Range:** Can add or subtract from the weapon's range or be left empty. Needs to handle cases where weapon range modifications could result in a zero or negative range.
- **Price and Weight:** Function same as other items.
- **Quantity:** Indicates how much ammunition is left.
- **Template:** Functions similarly to spell templates, but only one can be selected. (Selected option should remain displayed in the dropdown menu)
- **Conditions:** To be defined.
- **Damage:** Two operations - Addition and Override.
  - **Override:** Select Damage Category and Damage Type. Changes the weapon's damage type, under the defined category, to the specified damage type on the ammunition.
  - **Addition:** Define a roll formula and damage type to be added to the weapon's existing damage.

#### Nice to Have
- Prevent selecting the same Damage Category for override more than once.
- Manage cases where ammunition changes the weapon’s range or template after a token has been selected, ensuring conditions are met for valid target selection.

### Workflow
1. **Ammunition Creation and Management:**
   - Create ammunition items with specified fields in the Details section.
   - Manage quantities and attributes of ammunition within the character's inventory.
2. **Using Ammunition:**
   - Select ammunition from the inventory to use with a weapon.
   - Apply Range modifications to the weapon.
   - Apply Templates as defined.
   - Handle Conditions that affect which tokens can be targeted.
3. **Damage Calculation:**
   - Apply Override operations to modify the weapon's damage type based on the ammunition.
   - Apply Addition operations to add extra damage as specified by the ammunition.

### Acceptance Criteria
- [x] Ammunition items can be created with fields: Ammunition Type, Range, Price, Weight, Quantity, Template, Conditions, Damage.
- [x] Range field can add or subtract from weapon's range and handle edge cases.
- [x] Template field functions similarly to spells with a single selection.
- [x] Damage field supports both Override and Addition operations.
- [x] Ammunition can be selected and applied to weapons, affecting their attributes and attacks.
- [x] System prevents selecting the same Damage Category for override more than once.

**Comment by krbz999** [comment]
Ammunition applying a condition will be follow-up work once the system actually has any conditions.
