### ISSUE TITLE
Parrying and Blocking

### ISSUE THREAD

**Issue by Mythacri** [krbz999/artichron#23]
When damage is dealt to a character (by a weapon or a spell) they are able to parry and/or block the incoming damage. The character can spend 1 pip to block the damage with a  shield that they are holding and/or 1 pip to parry the damage with a weapon they are holding that has the parrying property. A character CAN spend 2 pips to use 2 different items they are holding and reduce the damage by the total amount.

Blocking: Shields are able to block and reduce the incoming damage by 4d6, 4d8, 4d10, and 4d12 respectively for the buckler, heater, kite, and tower shields.

Parrying: Weapons that are able to parry do so using an amount of dice equal to half their physical damage. A sword that deals 4d8 damage and has the parrying property can parry for half that damage rounded up. The base damage roll of the weapon is rolled and half of the result is used to parry.

The damage reduction caused by parrying and blocking goes at the very end of damage calculation. All other damage resistances and reductions are taken into account first. Parry and Blocking works on all damage types and not just on physical damage.

- [x] When you are applied damage, a popup should appear asking if you would like to parry or block with your equipped items
- [x] Player spends 1 pip per equipment they are using to parry.
- [x] ~~Shields need to have a blocking formula as well as a damage formula~~ OR a shield's damage formula is used for blocking and when bashing with a shield you deal half of the damage formula.

**Comment by krbz999** [comment]
Most of the points here have been implemented. The remaining to consider are:
- Implement the "pip" (or "action point") system.
- Should a weapon, shield, or spell that deals non-physical damage use those dice to block/parry with? Or is it restricted to the formulas that deal purely physical damage?

**Comment by Mythacri** [comment]
I would say non-physical damage should be included in the blocking/parrying. At least trying it out to start. If players worked to make the item stronger it should be allowed to be stronger.
