### ISSUE TITLE
On: Elixirs

### ISSUE THREAD

**Issue by krbz999** [krbz999/artichron#26]
### Buff
A "buff" type elixir can be used for 1 pip. Doing so will transfer one of its effects (buffs) to the owner of the elixir and expend 1 of its limited uses. Such an elixir must have at least 1 effect to choose from.

### Booster
A "booster" type elixir can only be used as part of a weapon attack or spell cast (not shields). This costs no pips, but expends any number of uses (for additional stamina during weapon attacks) or one use (for 1 additional mana during spellcasting).

- [x] #75
- [x] Allow spending stamina when blocking with a shield.
- [x] A booster can target only stamina or mana. It cannot target health.

### Restorative
A "restorative" type elixir can expend 1 of its limited uses (as well as costing 1 pip) to restore an amount of health.
- [x] The amount of health restored is configured directly on the elixir.
- [x] A restorative elixir can only restore health, it does not interact with stamina or mana.

**Comment by Mythacri** [comment]
I would suggest that a booster be used for shield items by Allowing the user to add additional dice to their opposing roll when attacked, further reducing damage.

**Comment by krbz999** [comment]
Convincing enough.

**Comment by krbz999** [comment]
#75

**Comment by krbz999** [comment]
It's still up for debate whether blocking/parrying should allow consuming elixirs, but this is done otherwise.
