### ISSUE TITLE
Skill Checks (For Discussion)

### ISSUE THREAD

**Issue by Mythacri** [krbz999/artichron#35]
# Edit: Edit: Current implementation:
> A formula of Xd6, which rolls X six-sided dice, and counts those that rolled a 6. The X is equal to the level an actor has in the relevant skill plus 1.

> It might be interesting to consider some skill thresholds that unlock additional bonuses. Completely arbitrary example: 4 levels of 'Throw' means when you use the Throw skill, dice explode on a 6.

---

Number of Skills:
Players have a number of skills from a list of 30 (pending). 10 skills related to each attribute between health, stamina, and mana.

Skill Check:
Skills are performed by rolling a pool of d6's in an effort to roll a 'hit' (a 6). The more proficient a character is at a skill the more d6's they roll. Players always will succeed at what they are doing but incur penalties to their own characters when they fail a skill check.

Failing a Skill Check:
Failing a skill check results in a player taking stress which causes detriments to other actions the character performs.

Succeeding a Skill Check:
A player succeeds on a skill check by landing a 'hit' on their dice. The more hits the player gets, the greater the level of success they achieve.

**Comment by krbz999** [comment]
Generally, when requestion a skill check, the GM would have a rough table in mind to determine the benefits or negative consequences of the roll. This is a result of the number of 6s rolled; each 'tier' reaps the benefits of the previous one in addition.


| Sixes Rolled | Result |
| --- | --- |
| 1+ | You did the thing and also this nice thing happened | 
| 3+ | An even better thing (or previous thing but improved) |
| 6+ | A really excellent thing (or previous thing improved even further |

**Comment by krbz999** [comment]
The list of skills, in which we are experimenting with having many specifically scoped skills, are divided into the categories 'Mind', 'Body', and 'Soul' (internal aliases: Live, Laugh, and Love). Some brainstormed ideas below:

### Mind
- Ward Detection (for detecting traps and magical wards)
- Knowledge (Religion)
- Knowledge (History)
- Knowledge (Magic)
- Knowledge (Science)
- Knowledge (Tech)
- Find Path (for navigation, finding location, tracking someone)
- Reason / Deduce
- Research
- Examine

### Body
- Drinking
- Heartiness (resisting elements)
- Dodging (possible duplicate here...)
- Trap Avoidance
- Jump
- Lift
- Throw / Kick
- Climb
- Swim
- Pickpocket

### Soul
- Menace (to intimidate)
- Persuade / Enthrall
- Mette (to steel one self)
- Avoid Enchantment
- Avoid Detection (sneaking)
- Understand / Insight
- Flirt
- Barter
- Bamboozle (lie)

**Comment by krbz999** [comment]
Even when rolling 10d6, the average number of 6s is something like 2-3.

It may be worth considering:
- A hit being 5+ (an average of 4 hits with 10d6).
- Using d4s.
- Using d8s and counting evens as hits.
- Rerolling 1s.
- Some other arbitrary measurement of success.

**Comment by krbz999** [comment]
Suggestion for the sheet layout.

![image](https://github.com/krbz999/artichron/assets/50169243/6502f756-51e5-4389-89a7-90a2d9b140ab)

**Comment by krbz999** [comment]
For now, I went with a formula of `Xd6even`, which rolls `X` six-sided dice, and counts those that rolled an even number. The `X` is equal to the level an actor has in the relevant skill.

**Comment by krbz999** [comment]
It might be interesting to consider some skill thresholds that unlock additional bonuses. Completely arbitrary example: 4 levels of 'Throw' means when you use the Throw skill, dice explode on a 6.

**Comment by krbz999** [comment]
> It might be interesting to consider some skill thresholds that unlock additional bonuses. Completely arbitrary example: 4 levels of 'Throw' means when you use the Throw skill, dice explode on a 6.

Such a bonus from reaching a threshold should not be required to be limited to the skill itself. For example 'arcane knowledge 10' might mean you can fuse more items than normal onto one target.

**Comment by krbz999** [comment]
Updated list after #41:

![image](https://github.com/krbz999/artichron/assets/50169243/ff4cce00-4823-4e4b-b892-2296a009483c)

**Comment by krbz999** [comment]
Items should be able to grant bonuses to skills in several ways.
- A bonus to a single skill.
- A bonus to an entire group of skills.
- A bonus to all skills.

A bonus can be one of two things:
- An increase to the level of the skill (additional dice rolled on skill checks).
- A bonus to the roll (a static number of guaranteed successes) which is much more powerful than a bonus to the level.

**Comment by krbz999** [comment]
The current implementation is not long-term feasible.
