### ISSUE TITLE
Consider the difference between a regular "Monster" sheet and that of a "Boss"

### ISSUE THREAD

**Issue by krbz999** [krbz999/artichron#37]
If there are any, at all. Maybe a "boss," whatever that means, can just use a Hero sheet.

**Comment by Mythacri** [comment]
The main difference between regular monsters and bosses would be:
- Special loot only found on bosses. These items are used to progress or 'level up' player characters
- Additional types of attacks and actions. Whereas regular monsters may have 1-3 options, bosses should have up to 5 options.
- Possibly multiple phases? New attacks and secondary health pools that are added as the fight goes on?

**Comment by krbz999** [comment]
Then it sounds like there should be no difference between a "monster" and "boss" sheet as all those things are possible on the new monster sheet.
