### ISSUE TITLE
Figure out the purpose of the dice "pools"

### ISSUE THREAD

**Issue by krbz999** [krbz999/artichron#4]
Why do they have dice here? We aren't using them.

- Mana is static in the spell building, with the size of the additional die depending on the type or shape of the spell.
- Spending stamina to increase the damage of a physical attack adds more dice of those that the weapon uses, not the stamina dice.
- Health...?

So, figure out their purpose.

**Comment by Mythacri** [comment]
Dice sizes for the dice pools are now being used for skill checks! See issue #5 for more details.
