### ISSUE TITLE
Determine the 'cap' for action points for actors that don't have "dice pools"

### ISSUE THREAD

**Issue by krbz999** [krbz999/artichron#45]
Building onto #34, since monsters don't have dice pools, some other value might be needed to 'cap' the additional d6s that a monster rolls for initiative when they have unspent action points.

**Comment by Mythacri** [comment]
Monsters should have a specific stat for action points. I would suggest not letting them gain additional action points between turns but that could be debated. This could be especially useful when balancing certain monsters. You could create large slow lumbering stacks of hit points and damage that are bested by speed for example.

I would, additionally, suggest that this action point number for each monster be based loosely on a tiered 'danger' system. Working on this in the meantime but just noting this here.

**Comment by krbz999** [comment]
Implemented `system.danger.value` for monster type actors.

At the start of each turn, a combatant starts with a number of action points according to their actor type.
- Hero: Size of their health pool (to be discussed).
- Monster: Three times their `system.danger.value` property.

A bonus number of AP is added on top equal to the number of turns the combatant is getting this round, multiplied by their `system.pips.turn` property (default '2'). Their level of the 'Hindered' condition is subtracted, and a combatant can start a turn with no fewer than 1 AP.

When rolling initiative, the additional d6s is capped by
- Hero: The size of their stamina pool.
- Monster: Three times their `system.danger.value` property.

All these numbers are still up for debate ofc.
