### ISSUE TITLE
Skill Checks / Dice

### ISSUE THREAD

**Issue by Mythacri** [krbz999/artichron#5]
When making a character in Artichron one of the first things to do is allocate dice to the three skills: Head, Hands, and Legs.

Head: Skills involving talking, perceiving, searching, or focusing.
Hands: Skills involving lifting, climbing, artistry, or hand-eye coordination.
Legs: Skills involving sprinting, jumping, dancing, or of course kicking in doors.

A player will have the choice of assigning a d12, a d8, and a d4 to their skills. The die size represents the character's level of proficiency with the assumed skills.

-------------------------

When making a character in Artichron one of the first things to do is select a favored attribute between Head, Hands, and Legs.

A player will have the choice of assigning a d6 to either Health, Stamina, or Mana; emphasizing which attribute they feel they are strongest in. The attributes that are not chosen will be assigned as the default d4's. Each attribute will start with the same amount of dice in their pool which is 3.

------------------------

When a skill check is needed the GM will have the player make a skill check using Head, Hands, or Legs along with Health, Stamina, or Mana. The player then rolls their assigned skill die + their assigned attribute die to determine their success! 

Note: Rolling these dice does not count as expending or using them and is merely a representation of the character's skill check.

-----------------------

With all of this in mind, the character sheets will need to include:

- [x] Health dice pool with the ability to adjust the number of dice and dice size
- [x] Stamina dice pool with the ability to adjust the number of dice and dice size
- [x] Mana dice pool with the ability to adjust the number of dice and dice size
- [ ] Head skill section with space for a few quick examples of associated challenges
- [ ] Hands skill section with space for a few quick examples of associated challenges
- [ ] Legsskill section with space for a few quick examples of associated challenges

**Comment by krbz999** [comment]
Piggybacking off this proposal, here is what I think would be needed for this to work:

- [ ] Add a button in the header to toggle the ability to Edit various, rarely changed properties of the actor (such as its image). When disabled, the actor image cannot be changed by clicking it on the 'Equipped' tab.
- [ ] When disabled, divide the 'Equipped' tab into three sections horizontally stacked (head, hands, legs).
- [ ] Clicking either section prompts the user to choose between Health, Stamina, or Mana, then performs the roll.
- [ ] The configuration menu for setting the value, max, and size of the pool dice gets redesigned to assign "d4", "d8", "d12" to one pool.
- [ ] The maximum value of each pool gets locked at "3" until we figure out a system that can increase this value through some kind of character progression.
- [ ] When not in "edit mode", the equipped items cannot be swapped out.

**Comment by krbz999** [comment]
All the functionality here has been implemented. Buttons have been added to the sheet in a stop-gap location; proper UI design will have to come at a later point.
