### ISSUE TITLE
Throwing Weapons

### ISSUE THREAD

**Issue by Mythacri** [krbz999/artichron#58]
Some weapons, such as daggers, should be able to be thrown at enemies as part of their attack. The thrown attributes works as such:

- [ ] The weapon generically can be thrown at a target within a range of 20. 
- [ ] The weapon is removed from being equipped after it is thrown
- [ ] Stamina can be expended to increase the range of the weapon by 5 for each point of stamina expended. (This one is under debate)

**Comment by krbz999** [comment]
Throwing what is normally a melee weapon can be done by creating an additional activity on the item.
