### ISSUE TITLE
Ignore any Changes on the automatically generated fusion effect if they exist on the Fusion option effect as well

### ISSUE THREAD

**Issue by InnilToo** [krbz999/artichron#62]
Prerequisite: https://github.com/krbz999/artichron/issues/60
In the item Fusion config tab add an option to set a value on fusion properties.
Examples:
* Set the value of Price to 100, the new fused item price will be incresed by 100.

**Comment by krbz999** [comment]
Perhaps the ActiveEffect used for the fusion option could simply take priority. E.g., if the effect would grant +5, then what the default would normally be for the same property is simply ignored.
