### ISSUE TITLE
Change the AP calculation to use Stamina instead of Health

### ISSUE THREAD

**Issue by InnilToo** [krbz999/artichron#64]
Current state: "For 'heroes', the amount of action points is equal to the size of their Health dice pool, plus 2 for each turn they take on this round, minus 1 for each level of the Hindered condition they are afflicted by, minimum of 1."

I propose we use the Stamina dice pool instead. It makes more sense than health.

**Comment by krbz999** [comment]
Need a journal entry page that describes what each dice pool does for a player, too. That is starting to become necessary.
