### ISSUE TITLE
Damage/Health Thresholds

### ISSUE THREAD

**Issue by NMyers17** [krbz999/artichron#89]
The purposes of these would be to signify for both Players and Monsters how hurt they are and therefore how close they are to death. The bonus points of seperating out health into catergories is that it allows for more interesting abilities, items and adds a layer of complexity to fights.

**Monsters**
For monsters these Thresholds should act like "Phases", a boss monster may have a certain set of abilities and act a certain way with normal health, but when they come bloodied, their abilities shift, they may gain additional resistances but lose their armour. The possibilites for this are quite literally endless.

It also adds a fun element to what may normally be a boring fight. And also helps to signify what monsters are "bosses" and what monsters are mobs.

**Thresholds:**
**Normal > Bloodied > Critical**

You could divide the health bar into 3 and gain these attributes. I think for Monsters this would work best. However for Players I think it work better as the following:
- Normal is 100% - 51% of Health.
- Bloodied is 50% - 21% of Health.
- Critical is 21% - 0% of Health.

**Players**
Adding Health Thresholds to characters will do 2 things: 
- Help characters signify to eachother how hurt they are. Adding an element of immersion as instead of "I've got 14 hit points" it becomes "I'm Critical" or "I'm bloodied".
- Adds interesting interactions with the main focus of the games which is the items.

If Items or even certain items behaved differently depending on what health state you were at this could add a level of risk vs reward to the game. If my spell is enhanced when I'm Critical, I could wade into the thick of things to increase the chance of that, however there is a possibility that shortly after or even before! I'll go down before pulling off the said move.
Again this doesn't need to be interactive items, maybe armour that is different the more you get hurt? Making you easier to hit but adding a reduction to incoming damage or vice versa.

Nothing written in stone, but the general ideas are here.

**Comment by krbz999** [comment]
There are multiple things here:
1) Indicating with an `ActiveEffect` that an actor is critical or bloodied.
2) Unlocking items or changes to the actor or their items.

I think point 2 needs some more examples, but point 1 sounds good to me as is.

**Comment by krbz999** [comment]
I'd say this was completed in the second testing milestone, save for the gating of features behind damage thresholds. Could you make a second issue for this?
